### ISSUE TITLE
Feature proposal: Allow wildcards in query / mutation paths

### ISSUE THREAD

**Issue by Coystark** [quasardd/react-query-boilerplate#3]
### Proposal

When building the query / mutation, it should be possible to put wildcards in the path.

### Solution

It can be similiar to next/router, example:

```
const {
  updateMutation
} = buildMutation({
  path: '/users/[id]',
});
```
And in the component level:

```
updateMutation({
  query: {
    id: 123,
  }
})
```

Also be possible to specify the query property inside mutate / mutateAsync methods.

**Comment by glothos** [comment]
That's a good improvement, totally agree. Any work done regarding that?

**Comment by Coystark** [comment]
> That's a good improvement, totally agree. Any work done regarding that?

Yep, here: https://github.com/quasardd/react-query-restful/tree/2-feature-proposal-allow-wildcards-in-paths

Its already done but I'll do more tests in the auto-invalidation feature in this weekend
